# Generated by Django 2.2.3 on 2020-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineApp', '0003_auto_20200113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='data',
            field=models.CharField(blank=True, max_length=270),
        ),
    ]
