# Generated by Django 2.2.3 on 2020-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineApp', '0005_auto_20200113_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='data',
            field=models.CharField(blank=True, max_length=270),
        ),
    ]
